name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: ex1
      id: ex1
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ex1
        setup-command: npm install
        command: npm test tests/ex1.spec.ts
        timeout: 10
        max-score: 10
    - name: ex2
      id: ex2
      uses: classroom-resources/autograding-command-grader@v1
      with:
        test-name: ex2
        setup-command: npm install
        command: npm test tests/ex2.spec.ts
        timeout: 10
        max-score: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        EX1_RESULTS: "${{steps.ex1.outputs.result}}"
        EX2_RESULTS: "${{steps.ex2.outputs.result}}"
      with:
        runners: ex1,ex2
